### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by L0cutus** [hkgnp/logseq-recurrence-plugin#1]
Hello

Latest logseq 0.59 nightly (17/2/2022) :
![recurrence](https://user-images.githubusercontent.com/90012/154700177-b2cd62ad-bf4b-4879-94ca-43ea2bb3acc4.gif)

Any idea?
Thanks!

**Comment by benjypng** [comment]
Can you try restarting Logseq?
If it still doesn't work, can you open up the Developer Console to see what
errors are there?

Developer Tools can be accessed in two other ways. At any point, you can
press Cmd + Opt + I on macOS or Ctrl + Shift + I on Windows or Linux.

**Comment by L0cutus** [comment]
Already done and installed version 0.60 :-)
![recurrence](https://user-images.githubusercontent.com/90012/154762169-9fdd0b83-53a2-4404-9b94-6e85f5cd3246.gif)

**Comment by benjypng** [comment]
Fixed in 1.0.4. Please update and try again.

**Comment by L0cutus** [comment]
> Fixed in 1.0.4. Please update and try again.

mmm seems there are some problems, it duplicates an event again and again :D
i have set a daily recurrence from 14/March to 20/March, one from 16/May to 22/May and one from 18/July to 31/July
after that i have found that ALL March day have the same recurrence and not only the one i have set 8-)
Now i have restored latest backup ;-)

{
  "disabled": true,
  "preferredDateFormat": "yyyy/MM/dd",
  "recurrences": [
    {
      "item": "Ferie Carmen",
      "dateAdded": 1645437837,
      "uuids": [
        "62133c7a-5724-4abe-8434-e65ccf77ba2d",
        "6213638d-dcbc-4e5d-9f74-4ac4498c4d72",
        "6213638d-1ae0-4a28-bd60-50b25ce74133",
        "6213638d-fc9a-4836-b181-13438e2f63e2",
        "6213638e-5c0d-4037-b560-b5c7a1e74d51",
        "6213638e-28be-4749-bff3-f2e9b17e3e7a",
        "6213638e-ef6b-43b8-a9ca-bcac551917a4",
        "6213638e-797f-4e5a-b6e2-18fe9fb38451",
        "6213638e-4c41-472e-b820-97311c82a785",
        "6213638e-1861-413b-982c-bc839e68e83e",
        "6213638e-00f4-4689-b8fe-73320682b73b",
        "6213638e-07f1-4e65-a004-b1320ad58c20",
        "6213638e-63f3-405d-b334-abd381e255cd",
        "6213638e-0373-4cf1-98bf-8415cab18b0e",
        "6213638e-2c2f-4eea-9ed0-7f078b4b0535",
        "6213638e-9bb2-4ea0-bdff-a480d1260b98",
        "6213638e-db5a-4015-9e46-9141fb1c9fc6",
        "6213638e-0233-4671-ab1f-be58a9bf983b",
        "6213638e-c2c3-4b6e-81dc-60c9b806498d",
        "6213638e-b272-43f1-aed2-8d3c6cffb1ce",
        "6213638e-6462-41f2-9536-52c7c2068fd9",
        "6213638e-2552-4cdd-841f-fa1c430e06f9",
        "6213638e-fb65-442f-b53e-a20e61720f08",
        "6213638e-9f75-42d9-8f40-9ab27e7d3aed",
        "6213638e-2310-44b8-abf8-a6e1135cdcac",
        "6213638e-2926-4ed0-a68a-220730401f00",
        "6213638e-836e-4233-b325-45982329355f",
        "6213638e-882c-483b-9c89-6303441843b0",
        "6213638e-15e5-4b50-acca-a63727661053",
        "6213638f-222b-4c99-a0af-e823d94da980",
        "6213638f-33ab-4127-8d2f-004b5826ff6e",
        "6213638f-2cf0-49f9-a337-f3f974466d97",
        "6213638f-0af2-46e3-b4dc-1c0ca2679bf7",
        "6213638f-1db9-4ab9-acdf-845cd8e5f865",
        "6213638f-ae04-425c-b9cd-87b211fdafed",
        "6213638f-1d97-4723-86c3-caa1df2aa60c",
        "6213638f-cf7c-4e60-aca0-0db2545652b1",
        "6213638f-55a8-4fb6-9498-5b7eedf3b16c",
        "6213638f-d816-43d9-9866-24211cc9c271",
        "6213638f-61bc-43f9-80ab-eba96cb5f844",
        "6213638f-5e16-4b38-b5a5-8ae6461c1000",
        "6213638f-2dbc-42c9-948a-cff8cd8cb5ca",
        "6213638f-c3e8-42a7-82cb-dab0fcda95f4",
        "6213638f-8f47-4b30-9392-a3e464a972bf",
        "6213638f-7958-41c2-86bd-06b326a04bb6",
        "6213638f-5ed9-4e8e-8be0-3d6fec78fb26",
        "6213638f-72e6-4818-97d4-1e597a29e6cc",
        "6213638f-809d-4040-b999-e290c94fc78e",
        "6213638f-3b32-45ef-8205-62274e4baf11",
        "6213638f-f318-4533-92e5-1be8c405c049",
        "6213638f-ece1-4602-a0c0-6b587c4ed2cf",
        "62136390-4a19-48a0-9618-05447a12c66c",
        "62136390-c277-4342-ab42-d180b583c831",
        "62136390-ac0b-4580-9676-cdd3ed6c10de",
        "62136390-17fb-4623-8834-9c042945687b",
        "62136390-dadf-49ff-aadd-ce799d399b4b",
        "62136390-7e21-4a62-a812-bf7d799bbd67",
        "62136390-1d32-41b1-893b-42e5fdb02c6c",
        "62136390-b2f3-4f43-94d7-4695c54c8cf6",
        "62136390-5bb1-473a-aeba-ee1d4b994ad0",
        "62136390-79e6-4760-9a28-0c7291ecb77e",
        "62136390-5e43-41ce-86fa-26765ebe8632",
        "62136390-9504-4b7e-b0b6-0ca23bb7b8c5",
        "62136390-7f84-4ce8-a522-b4fa639f0930",
        "62136390-54a0-4ff9-a0ea-912936a3518d",
        "62136390-8504-4de6-bf33-0b088fdfa32c",
        "62136390-54ab-437e-99f1-1da350842da2",
        "62136390-151f-49b2-b723-01f7b3b9767b",
        "62136390-ac4b-4ef5-90c9-1f5dbb89aea8",
        "62136391-e900-45fd-a2d4-54074f8c01f2",
        "62136391-4184-461d-b7fd-85e632843986",
        "62136391-6954-40a2-8191-696187c32c48",
        "62136391-3f88-42d6-afb2-cf8e8010ae97",
        "62136391-2474-4821-93ca-173053107def",
        "62136391-116e-44d5-a7eb-c8990da97153",
        "62136391-f923-4ea6-903c-4bcfa42c6428",
        "62136391-030d-490e-98a9-ee03309d8f41",
        "62136391-dd6c-4db6-b39a-6f1dae454609",
        "62136391-297d-4250-890f-e1df90a673bd",
        "62136391-c9d3-4692-82c9-8521a56e198f",
        "62136391-6c60-410d-8965-7141fb2ff80a",
        "62136391-39d9-406d-a984-5fa443c861d0",
        "62136391-c897-4f44-963a-fc01a456018c",
        "62136391-f472-4f44-a995-6be4d8409f6a",
        "62136391-622e-4d15-aa0d-85a02d611f36",
        "62136391-4abb-4431-bc79-3630bada3f0d",
        "62136391-e90d-42ef-be52-ea928fd758ea",
        "62136391-318d-4911-ad4c-59bafa5d0550",
        "62136391-640b-4299-a475-25d085d50c95",
        "62136392-8afc-4d34-bff5-4442c45b2e5b",
        "62136392-e3c5-413a-80cb-b90455395bf2",
        "62136392-971c-4630-9011-fc14d5aed2f1",
        "62136392-d91b-43a8-b90b-bee5990af67c",
        "62136392-2465-4883-b005-3660cd2ca5fe",
        "62136392-e8da-42fd-8856-db4246e45bd3",
        "62136392-08ab-48de-a59a-926e33e8d201",
        "62136392-f345-4943-b955-01ba0477d867",
        "62136392-ff14-4f67-9b36-ec1f7e1f00a6",
        "62136392-216b-4385-b412-5abc3acbb83c",
        "62136392-c494-4e15-9cb7-fe82d06ba907",
        "62136392-499b-42c5-8ac7-88776e80151d",
        "62136392-decb-46a5-9efd-7b0bddaf1e77",
        "62136392-f37c-4b83-8860-66b41b5869fe",
        "62136392-57c7-471f-830f-fc9552cd7d12",
        "62136392-49b0-436e-b6b8-f99c8c3dcf3a",
        "62136392-d9e4-43fe-bceb-9bf76fef9df9",
        "62136392-7e18-4b1e-b9cf-05af615aac6e",
        "62136393-22df-4016-9ada-d4b50c360f4c",
        "62136393-f699-4bb2-8b87-9d2a9127e9bb",
        "62136393-8abe-4650-b00a-651fdd259291",
        "62136393-7f3a-41d1-93af-7646abb60e06",
        "62136393-0b9d-4afe-841a-f58698beb312",
        "62136393-a554-4e67-a4e3-6b8c41e8a125",
        "62136393-9e34-47ee-a0bc-57a62912c93e",
        "62136393-3585-4f60-9b23-728c062861bd",
        "62136393-2145-4fe0-b88a-505cc801136c",
        "62136393-6ca4-4e8d-85ef-6aac725b3590",
        "62136393-dfdc-4144-8673-58ab42612ddc",
        "62136393-4027-4de5-a6df-f3e1bb506d47",
        "62136393-7478-4f3d-8742-3aced7b90d27",
        "62136393-52e7-48c6-97be-e233cc785f4a",
        "62136393-9f0e-44b5-b64c-b21b665e51c1",
        "62136393-c1b0-49c3-84e7-25ad2dc818c1",
        "62136393-2a93-43e6-859f-68d2541da1fa",
        "62136393-5416-45d7-9f23-e33fae34d189",
        "62136393-30c4-4151-8440-e239a43a34eb",
        "62136393-827b-4c11-859c-c9317632fe73",
        "62136393-56b5-42ec-aa6a-9375ce3e2328",
        "62136393-4572-460c-9a35-285486de8cca",
        "62136393-836c-424b-a2e6-7dbc47e986ba",
        "62136394-7da6-4a20-950a-9ed27c5d67fc",
        "62136394-f1d7-439a-82a5-3ddc141c15c4",
        "62136394-0d40-4e92-bdfb-17aa93db58e8",
        "62136394-b18e-41a4-93e4-c5837381e4e1",
        "62136394-b99a-44e3-8ee3-c8025a230e27",
        "62136394-ffc8-4aeb-8cd4-7054bbd1c9b7",
        "62136394-d11b-451c-840f-ca093ebdaf03",
        "62136394-cbfa-4931-ba32-a8ea3cdbc7b3",
        "62136394-37a7-4ebb-8ebe-9ffc4dca8c34",
        "62136394-f095-4f3a-b92d-11a4a9eb8ce0",
        "62136394-a0d9-499d-a469-41011fa32ee8",
        "62136394-766a-4185-8949-170584cf29d7",
        "62136394-1b82-405f-a05d-c34c74d378cf",
        "62136394-f081-4781-9519-20e9be56633a",
        "62136394-d389-4d85-a7d5-1e331e136457",
        "62136394-7449-4219-a63e-2c67a525029c",
        "62136394-3b72-4674-8609-cdfcb7192ea8",
        "62136394-c9ff-487a-bac9-51b78256b619",
        "62136394-bb61-4098-8194-984709a6ad02",
        "62136394-ba23-447f-83eb-48be5e49e02d",
        "62136394-dc79-4acf-b32c-1f861a51f67b",
        "62136394-908a-4932-80a6-298e62f93a8a",
        "62136394-134d-43bc-beae-a09ad000ad6f",
        "62136394-465c-4f78-bfbc-286fa8eee331",
        "62136394-f5fa-4f5c-b037-0a994164d186",
        "62136394-e61a-4000-ae8a-daba204018a5",
        "62136394-0302-43ab-8f9a-e78200c1925f",
        "62136394-ddf2-4b41-bbca-2b6f00d02c91",
        "62136394-d15c-4b53-a2bc-4cc0e94158c7",
        "62136394-db52-4497-a1e9-4979d03e11b5",
        "62136394-424e-434e-95a3-57ff4de61a20"
      ]
    }
  ]
}

**Comment by benjypng** [comment]
Are they all for the same item?

**Comment by L0cutus** [comment]
Don't know, must retry with different text

**Comment by georgd** [comment]
I’m experiencing something similar: I have two different items with different text. One should recur every Tuesday until end of March, the other on the three Thursdays to come. Setting recurrence for the first added all of them to the Mondays (in the correct weeks). Setting the recurrence for the latter added another bunch of the former to the Mondays in the appropriate weeks.

**Comment by benjypng** [comment]
Apologies, I've not catered for a scenario where you would create recurrence from any other day except today.

Have implemented this in 1.0.5. Can update and give it a try.

**Comment by georgd** [comment]
Great, thanks! That fixed it for me.

**Comment by L0cutus** [comment]
> Great, thanks! That fixed it for me.

Confirmed thanks!

**Comment by auspiciouslink** [comment]
How can I set when the recurrence is supposed to happen? I can't figure out how I can set this with the start-time:: and end-time:: when I want to schedule the event to recur on a day other than today?

Like, if today is Monday and I want to create an event for every Wednesday, how do I do this?
