### ISSUE TITLE
How do I remove a recurring block?

### ISSUE THREAD

**Issue by aabs** [hkgnp/logseq-recurrence-plugin#2]
I mistakenly created a daily recurring block, and now realising my mistake, I'd like to remove them all.  Is there a way?

**Comment by benjypng** [comment]
If you open up the Recurring popup again, you should be able to see the recurrence you set. Just hit `Delete` next to it.

**Comment by DannySu09** [comment]
> If you open up the Recurring popup again, you should be able to see the recurrence you set. Just hit `Delete` next to it.

Hi, I have a similar problem. I couldn't find the recurrence I set before from the popup. 

And I may have made the problem more complex, for i also deleted the plugin and found the recurring block still keep appearing on journal page.

Seems like the plugin still exist on somewhere and mange to take effect?

**Comment by benjypng** [comment]
> I mistakenly created a daily recurring block, and now realising my mistake, I'd like to remove them all. Is there a way?

<img width="671" alt="Screenshot 2022-03-12 at 12 17 00 PM" src="https://user-images.githubusercontent.com/47936793/158003326-4d4e2342-a180-4b10-858f-ec26b81eb6cc.png">

You should see saved recurrences under the section 'Saved Recurrences' (as shown in the image above). Just click 'Delete' next to it.

**Comment by benjypng** [comment]
> > If you open up the Recurring popup again, you should be able to see the recurrence you set. Just hit `Delete` next to it.
> 
> Hi, I have a similar problem. I couldn't find the recurrence I set before from the popup.
> 
> And I may have made the problem more complex, for i also deleted the plugin and found the recurring block still keep appearing on journal page.
> 
> Seems like the plugin still exist on somewhere and mange to take effect?

Please see the post [above](https://github.com/hkgnp/logseq-recurrence-plugin/issues/2#issuecomment-1065809832) on how to delete a Saved Recurrence.

Deleting the plugin does not actually delete recurrences since upon creating the recurrence, the blocks are immediately written to your graph. The only way to delete them after you delete the plugin is to delete them manually.

**Comment by DannySu09** [comment]
> Deleting the plugin does not actually delete recurrences since upon creating the recurrence, the blocks are immediately written to your graph. The only way to delete them after you delete the plugin is to delete them manually.

Thanks for replying. I reinstalled the plugin, set recurrence on the blocks that have been set as recurrence before, and then deleted the recurrence. Now, the problem seems gone.

**Comment by DannySu09** [comment]
> > Deleting the plugin does not actually delete recurrences since upon creating the recurrence, the blocks are immediately written to your graph. The only way to delete them after you delete the plugin is to delete them manually.
> 
> Thanks for replying. I reinstalled the plugin, set recurrence on the blocks that have been set as recurrence before, and then deleted the recurrence. Now, the problem seems gone.

Hi, @hkgnp, sorry for further bothering. The recurrence blocks occur again in today's journal. Could you tell me how to perform the manual deletion as you [mentioned above](https://github.com/hkgnp/logseq-recurrence-plugin/issues/2#issuecomment-1065809983)? Thanks!

**Comment by benjypng** [comment]
Oh what I meant was to manually go to each page and remove the block from those pages.

**Comment by benjypng** [comment]
> > Deleting the plugin does not actually delete recurrences since upon creating the recurrence, the blocks are immediately written to your graph. The only way to delete them after you delete the plugin is to delete them manually.
> 
> Thanks for replying. I reinstalled the plugin, set recurrence on the blocks that have been set as recurrence before, and then deleted the recurrence. Now, the problem seems gone.

I think this will not work as the blocks generated may have a different ID

**Comment by DannySu09** [comment]
> Oh what I meant was to manually go to each page and remove the block from those pages.

This can't solve the problem. The blocks will also occur on new journal page that is automatically created by Logseq everyday.

**Comment by benjypng** [comment]
Hmm then I don't think it may have anything to do with the plugin. When you
click Create Blocks, the plugin just creates the blocks based on the form.
If they journal pages do not exist, it creates them. To go to these pages,
download the journal calendar plugin and go to those dates to delete the
blocks.

**Comment by benjypng** [comment]
You can also go to your file manager and navigate the `journals` folder and just delete all the journal pages in the future. That would delete the blocks as well, assuming that you have not created any other blocks in the future as well.

If you are still facing a problem, please re-open this issue. If not, am closing it due to inactivity.
